#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (! file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
    fwrite(STDERR, "[artisan] Composer dependencies are not installed. Run 'composer install' inside the app container.\n");
    exit(1);
}

require $autoload;

$app = require __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);